apiVersion: v1
kind: Pod
metadata:
  name: ansible-pod
spec:
  containers:
    - name: ansible
      image: ansible-in-k8s
      volumeMounts:
        - mountPath: /ansible
          name: ansible-volume
  volumes:
    - name: ansible-volume
      emptyDir: {}
